# Generated by Django 5.2.3 on 2025-10-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
    ]
