# Generated by Django 5.2.3 on 2025-09-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='precio',
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidades',
            field=models.ManyToManyField(related_name='doctores', to='doctores.especialidad'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DoctorEspecialidad',
        ),
    ]
