# Generated by Django 5.2.3 on 2025-12-15 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0002_remove_especialidad_precio_doctor_especialidades_and_more'),
        ('pacientes', '0003_historico'),
        ('procedimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=100)),
                ('doctor_nombre', models.CharField(max_length=50)),
                ('arancel_descripcion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('estado_pago', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=50)),
                ('arancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='procedimientos.arancel')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_deleted', to=settings.AUTH_USER_MODEL)),
                ('doctor_especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='doctores.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
