# Generated by Django 5.2.3 on 2026-07-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_arancel_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='arancel_precio',
            new_name='arancel_precio_debito',
        ),
    ]
