# Generated by Django 5.2.3 on 2026-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_rename_arancel_precio_cita_arancel_precio_debito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='arancel_precio_debito',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
    ]
