# Generated by Django 5.2.3 on 2026-07-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_arancel_precio_debito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='arancel_precio_debito',
        ),
    ]
