# Generated by Django 5.2.3 on 2026-07-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_cita_arancel_precio_debito'),
        ('procedimientos', '0002_alter_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='arancel_precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='debito_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, default=250.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='procedimientos.detallefactura'),
        ),
    ]
