# Generated by Django 5.2.3 on 2026-07-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_arancel_precio_cita_debito_fijo_cita_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
